on:
  push:
    branches:
      - "graal-build"
jobs:
  build-jar:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/cache@v2"
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: "${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}"
      - uses: "DeLaGuardo/setup-clojure@4.0"
        with:
          cli: "1.10.3.1075"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - run: "clojure -A:dev -M --report stderr -m moclojer.build"
        env:
          CI_COMMIT_SHA: "${{ github.sha }}"
      - uses: "actions/upload-artifact@v2"
        with:
          name: "moclojer-${{ github.run_id }}-jar"
          path: |
            target/*.jar
  build-native:
    needs: "build-jar"
    runs-on: "${{ matrix.os }}"
    name: "Build native image on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ "macos-11", "ubuntu-20.04" ]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "graalvm/setup-graalvm@v1"
        with:
          version: "22.0.0.2"
          java-version: "17"
          components: "native-image"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: "actions/download-artifact@v2"
        with:
          name: "moclojer-${{ github.run_id }}-jar"
      - run: "native-image @${{ runner.os }}-native-image-args"
      - uses: "actions/upload-artifact@v2"
        with:
          name: "moclojer-${{ runner.os }}-${{ github.run_id }}-bin"
          path: |
            moclojer
