name: linter

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: DeLaGuardo/setup-clj-kondo@v1
      with:
        version: '2022.04.25'
    - uses: actions/checkout@v2.3.3
    - name: clj-kondo
      run: clj-kondo --lint src test
