name: release

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

permissions:
  contents: write

jobs:
  call-build:
    uses: moclojer/moclojer/.github/workflows/build-native-image.yml@main

  release:
    needs: "call-build"
    runs-on: "ubuntu-20.04"
    environment: release
    steps:
    - uses: actions/checkout@v3
    - uses: "actions/download-artifact@v3"
      with:
        name: moclojer_bin_Linux
        path: moclojer_Linux
    - uses: "actions/download-artifact@v3"
      with:
        name: moclojer_bin_macOS
        path: moclojer_macOS
    - uses: "actions/download-artifact@v3"
      with:
        name: moclojer_jar
        path: moclojer.jar
    - name: Set release name
      run: echo "RELEASE_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.RELEASE_NAME }}
        files: |
          moclojer_Linux
          moclojer_macOS
          moclojer.jar

  call-docker:
    needs: "release"
    uses: moclojer/moclojer/.github/workflows/docker.yml@main
